import enum

class UserRole(str, enum.Enum):
    STUDENT = "STUDENT"
    FACULTY_ADVISOR = "FACULTY_ADVISOR"
    COORDINATOR = "COORDINATOR"
    HOD = "HOD"
    DEAN = "DEAN"
    MASTER_ADMIN = "MASTER_ADMIN"

class OdStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    PENDING_FACULTY = "PENDING_FACULTY"
    FACULTY_APPROVED = "FACULTY_APPROVED"
    FACULTY_REJECTED = "FACULTY_REJECTED"
    PENDING_COORDINATOR = "PENDING_COORDINATOR"
    APPROVED_AWAITING_EVIDENCE = "APPROVED_AWAITING_EVIDENCE"
    PENDING_EVIDENCE_FACULTY = "PENDING_EVIDENCE_FACULTY"
    PENDING_EVIDENCE_COORDINATOR = "PENDING_EVIDENCE_COORDINATOR"
    EVIDENCE_REVISION_REQUESTED = "EVIDENCE_REVISION_REQUESTED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
