org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Gradle & Kotlin build performance and incremental cache flags
org.gradle.caching=true
org.gradle.parallel=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=false
