"""Add cgpa attendance residence_type parent_consent_url

Revision ID: c02772641943
Revises: '43a4d3a58620'
Create Date: 2026-08-02 15:12:41.812493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02772641943'
down_revision: Union[str, None] = '43a4d3a58620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('od_requests', sa.Column('cgpa', sa.Float(), nullable=True))
    op.add_column('od_requests', sa.Column('attendance_percentage', sa.Float(), nullable=True))
    op.add_column('od_requests', sa.Column('residence_type', sa.String(length=20), nullable=True, server_default='Day Scholar'))
    op.add_column('od_requests', sa.Column('parent_consent_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('od_requests', 'parent_consent_url')
    op.drop_column('od_requests', 'residence_type')
    op.drop_column('od_requests', 'attendance_percentage')
    op.drop_column('od_requests', 'cgpa')
    # ### end Alembic commands ###
