"""Add faculty_approval_time

Revision ID: da1187d61e3e
Revises: '2026_08_06_1800'
Create Date: 2026-08-07 11:17:25.235800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1187d61e3e'
down_revision: Union[str, None] = '2026_08_06_1800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.add_column('od_requests', sa.Column('faculty_approval_time', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('od_requests', 'venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('od_requests', 'organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('od_requests', 'residence_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Day Scholar'::character varying"))
    op.create_index(op.f('ix_od_requests_faculty_id'), 'od_requests', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_od_requests_status'), 'od_requests', ['status'], unique=False)
    op.create_index(op.f('ix_od_requests_student_id'), 'od_requests', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_od_requests_student_id'), table_name='od_requests')
    op.drop_index(op.f('ix_od_requests_status'), table_name='od_requests')
    op.drop_index(op.f('ix_od_requests_faculty_id'), table_name='od_requests')
    op.alter_column('od_requests', 'residence_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Day Scholar'::character varying"))
    op.alter_column('od_requests', 'organizer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('od_requests', 'venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('od_requests', 'faculty_approval_time')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    # ### end Alembic commands ###
